name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environnement à détruire'
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  TF_VERSION: '1.14.0'

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - run: terraform init -backend-config="bucket=tfstate-fmt-${{ inputs.environment }}"
      - run: terraform destroy -var-file=envs/${{ inputs.environment }}/terraform.tfvars -auto-approve
